//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Sistema_Cadastro.Models
{
    
    
    public partial class funcionario
    {
        public int funcionarioId { get; set; }

        public string nome { get; set; }

        public string departamento { get; set; }

        public string cargo { get; set; }

        public string email { get; set; }
    }
}
